### DISCUSSION TITLE
pyo3 compilation

### DISCUSSION THREAD

**Discussion by Sytten** [cross-rs/cross#1247] [General]
Hi there!

We are trying to cross-compile pyo3 to embed a python interpreter in our rust binary, this is proving to be a challenge and I was wondering if someone else had that working? We will have to build custom images, but any tips is appreciated.

Thanks

**Comment by Emilgardis** [comment]
The steps how to do this seem to be pretty well documented on 

https://pyo3.rs/main/building_and_distribution.html#cross-compiling


So, should be something like

```toml
[build]
pre-build = "apt-get update && apt-get -y install python3.7"
[build.env]
passthrough = [
    "PYO3_CROSS=1",
]
```

**Reply by Sytten** [reply]
Good starting point, having some trouble with it because the image seems to be based on ubuntu 16.04 for some reason instead of ubuntu 20.04 so python 3.7 is not present. We also need to get a python built for the target distribution.

EDIT: I found out that 0.2.5 is still 16.04 and 20.04 will be in 0.3.0!

**Reply by Emilgardis** [reply]
Maybe it'll suffice with `libpython3.8-dev:$CROSS_DEB_ARCH`? (couldn't find 3.7-dev in focal)

so

```toml
[build]
pre-build = "apt-get update && apt-get -y install libpython3.8-dev:$CROSS_DEB_ARCH"
```

if you want to use a dockerfile, you can do that also with 

```toml
[build]
dockerfile = "Dockerfile"
```
_see [wiki](https://github.com/cross-rs/cross/wiki/Configuration#builddockerfile)_

and cross will automatically build it and use it.
