### DISCUSSION TITLE
Is there any way to cross build aarch64-pc-windows-msvc and darwin?

### DISCUSSION THREAD

**Discussion by mobeicanyue** [cross-rs/cross#1286] [Q&A]
now i want to compile aarch64-pc-windows-msvc on windows now in github action.
```
# windows
          - target: x86_64-pc-windows-msvc
            release-name: x86_64-windows
            suffix: .exe
            use-cross: false

          - os: windows-latest
            target: aarch64-pc-windows-msvc
            suffix: .exe
            use-cross: true
```

x86_64 is successed but aarch failed because of

![image](https://github.com/actions-rs/cargo/assets/81098819/73c9264b-843c-4b63-b224-dec7508890f2)

how can i do?
Is there any way to cross build aarch64-pc-windows-msvc and darwin?

**Comment by Emilgardis** [comment]
See https://github.com/cross-rs/cross-toolchains for msvc, we (as in the cross-rs team) don't distribute an image of it due to licensing in microsoft TOS

**Reply by mobeicanyue** [reply]
I would like to understand the distinction between cross build and cargo build.

As I understand it, cross provides the necessary target environment for the build process, whereas cargo does not offer this feature. However, when building a target within the context of GitHub Actions, we have access to three machine types: Windows, Linux, and macOS. According to my search, they all seem to be of x86-64 architecture

Considering these native compilation environments, would it be acceptable to use cargo build with x86-64 to compile for aarch64? Is this approach viable?

**Reply by mobeicanyue** [reply]
What I want to know is, is it feasible to compile executable files of different architectures of this system through 'cargo' under the same system? If it is feasible, then there should be no need to worry about the image problem of 'cargo'

**Reply by Emilgardis** [reply]
yes, it's totally feasible, infact cross does just that when compiling for aarch64 (and other "exotic" architectures), we just setup the environment to do so in a container running x86_64 linux.

When compiling for windows aarch64 msvc, you need the visual studio for arm64 installed, seems like githubs [`windows-2022`](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#workloads-components-and-extensions) and [`windows-2019`](https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md#workloads-components-and-extensions) runner have a bunch of arm64 vc packages installed, so it might work out of the box without having to use cross.

**Reply by Emilgardis** [reply]
The only distinction between `cross build` and `cargo build` is that `cross build` will run `cargo build` inside a docker container with standard C/C++ dev tools and libraries (or some other enironment with [configuration](https://github.com/cross-rs/cross/wiki/Configuration))

rustc itself is perfectly capable of cross-compiling without these tools and libraries (except for maybe needing to have a linker installed for the target)

**Comment by mobeicanyue** [comment]
So i can solely use `cargo` to build aarch64 windows on x86-64 windows without `cross`? Same as mac darwin

here is my github action code, could you check it for me?

```
name: Release

on:
  push:
    tags:
      - 'v*.*.*' 

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

  
jobs:
  release:
    name: Cross build for ${{ matrix.release-name }}
    runs-on: ${{ matrix.os }}
    env:
      build_filename: network-master${{matrix.suffix}}
      new_filename: X;1145${{matrix.suffix}}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          # linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            release-name: x86_64-linux
            suffix: ""
            use-cross: true

          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            release-name: arm64-linux
            suffix: ""
            use-cross: true

          # apple
          - os: macos-latest
            target: x86_64-apple-darwin
            release-name: x86_64-macos
            suffix: ""
            use-cross: false

          - os: macos-latest
            target: aarch64-apple-darwin
            release-name: arm64-macos
            suffix: ""
            use-cross: true

          # windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            release-name: x86_64-windows
            suffix: .exe
            use-cross: false

          - os: windows-latest
            # Many compilation tools have insufficient support for arm64 windows
            target: aarch64-pc-windows-msvc
            release-name: arm64-windows
            suffix: .exe
            use-cross: true


    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install Protoc
        if: matrix.os == 'windows-latest'
        uses: arduino/setup-protoc@v2
        with:
          version: '23.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Cross
        uses: actions-rs/cargo@v1
        with:
          command: install
          use-cross: false
          args: cross --git https://github.com/cross-rs/cross

      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: ${{ matrix.use-cross }}
          args: --release --target=${{ matrix.target }}
```
