### DISCUSSION TITLE
Cross compiling crate with git-version

### DISCUSSION THREAD

**Discussion by ondrowan** [cross-rs/cross#1473] [Q&A] [answered]
My crate depends on `git-version`. After running  `cross run --target aarch64-unknown-linux-gnu` it complains that:

> git describe exited with status 128: fatal: detected dubious ownership in repository at ...

It's most likely caused by the git directory having a different owner than the user that's running `cargo` command inside of the Docker container. Is it possible to somehow change the ownership here? I couldn't find anything in the documentation.

The minimal repro case is here: https://github.com/ondrowan/cross-git-version/tree/master

**Comment by Emilgardis** [comment]
there's no good way to solve this, except doing `git config --system --add safe.directory /some/path` inside the container using pre-build

I'm sure we can make it better, but I'm not certain

```toml
[build]
pre-build = ["git config --system --add safe.directory /some/path"]
```

**Reply by Emilgardis** [reply]
one immediate improvement I see is that we could provide the workdir

**Reply by Emilgardis** [reply]
Created https://github.com/cross-rs/cross/issues/1474 for this

**Reply by ondrowan** [reply]
Is there any other way to get something similar to `$CROSS_WORKDIR` at the moment? From what I've tried it seems that hardcoding the path is the only way to achieve this, which doesn't really work when using multiple environments.

**Reply by Emilgardis** [reply, marked as answer]
looks like 

```toml
[build]
pre-build = ["git config --system --add safe.directory '*'"]
```

works, which should be universal!
