### DISCUSSION TITLE
Expected behaviour of build.env.passthrough in 0.2.2?

### DISCUSSION THREAD

**Discussion by SanityOverflow** [cross-rs/cross#862] [Q&A] [answered]
I recently updated cross to 0.2.2, and noticed that env passthrough via `build.env` doesn't seem to work the same way as in 0.2.1.

For a minimal reproduction, if I have a `Cross.toml` file like so in any Rust project (e.g. just run `cargo init`):

```toml
[build.env]
passthrough = ["CARGO_TERM_COLOR"]
```

and run:

```bash
CARGO_TERM_COLOR=never cross build --target aarch64-unknown-linux-gnu
```
this will still give me a coloured output, as if the env var was not set or passed through. Note that in 0.2.1, this will give me an uncoloured output.

However, if in 0.2.2, I instead write:

```toml
[target.aarch64-unknown-linux-gnu.env]
passthrough = ["CARGO_TERM_COLOR"]
```

and run the same command as above, then it will work properly.

I'm not sure if this is expected behaviour or not, hence why I didn't reporting it as a bug/issue. Was the previous behaviour in 0.2.1 changed such that this is intended?

For context, this is actually causing issues for me as I used to use an environment variable to trigger certain actions. As such, I would like to know if this is intended or not so I can adjust my GitHub workflows accordingly.
