### ISSUE TITLE
Allow setting `dockerfile.platform` or similar

### ISSUE THREAD

**Issue by Emilgardis** [cross-rs/cross#1096]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [ ] This feature could be solved with a [custom docker image](https://github.com/cross-rs/cross#custom-docker-images) (optional)

### Describe your request

When specifying a `dockerfile` to build, it could be helpful to restrict the allowed platforms.

To do that today, you can do the following

```toml
[target.x86_64-unknown-linux-gnu]
dockerfile.file = "Dockerfile"
image.name = "my-image"
image.toolchain = ["x86_64-unknown-linux-gnu"]
```

It'd be good to have something like

```toml
[target.x86_64-unknown-linux-gnu]
dockerfile.file = "Dockerfile"
dockerfile.toolchain = ["x86_64-unknown-linux-gnu"]
```
