### ISSUE TITLE
Cannot set glibc version in x86_64-unknown-linux-gnu target

### ISSUE THREAD

**Issue by Geocld** [cross-rs/cross#1101]
Hi, I am trying compile a x86_64-unknown-linux-gnu target with glib 2.17, my `Cross.toml` is:

```
[target.x86_64-unknown-linux-gnu]
version = "2.17"
```

when I run `cross build --release --target x86_64-unknown-linux-gnu`, I get these warnings:

```
[cross] warning: found unused key(s) in Cross configuration:
 > target.x86_64-unknown-linux-gnu.version

```

How to fix this it?

**Comment by Emilgardis** [comment]
Hi!

There is no `version` key for this target. if you want `2.17`, consider using the centos image

```toml
[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:0.2.4-centos"
# or for the latest image on `main`
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main-centos"
```

the `version` key is available when using zigbuild, see https://github.com/cross-rs/cross/wiki/Configuration#targettargetzig
