### ISSUE TITLE
Enable parsing config values in virtual manifests

### ISSUE THREAD

**Issue by sondre-teigen** [cross-rs/cross#1158]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [ ] This feature could be solved with a [custom docker image](https://github.com/cross-rs/cross#custom-docker-images) (optional)

### Describe your request

Cross should be able to parse config values from `[workspace.metadata.cross]` sections. 

### Describe why this would be a good inclusion for `cross`

It seems to be impossible to set per-workspace config values when using virtual manifests without editing `Cross.toml`, since `[package.metadata]` sections do not work in virtual manifests. 

An applicable scenario would be when the `CROSS_CONFIG` variable is set to a global, constant, `Cross.toml` file.

**Comment by Alexhuszagh** [comment]
Related to #842.

**Comment by Emilgardis** [comment]
Hmm, this is an unfortunate situation.

Currently, as we support `package.metadata.cross`, we technically should support multiple of those and with this feature implemented `workspace.metadata.cross`. This however presents a problem.

Say I have the following workspace (which is a virtual manifest with `foo` and `bar` members)


```toml
# Cargo.toml

[package]
name = "foo"
# ...
[package.metadata.cross]
build.image = "my_foo_image"

[workspace]
members = "bar"
[workspace.metadata.cross]
build.image = "my_workspace_image"


# bar/Cargo.toml

[package]
name = "bar"
[package.metadata.cross]
build.image = "my_bar_image"
```

what image should we use on `cross build`, `cross build -p foo` and `cross build -p bar`?
This is even more confusing when you consider values which append when merging.

I think the solution is to only read `workspace.metadata.cross`, or `package.metadata.cross`, but only allow one `package.metadata.cross`
