### ISSUE TITLE
Fails to install cross

### ISSUE THREAD

**Issue by salman01zp** [cross-rs/cross#1177]
I tried to install cross on Linux env using `cargo install cross --git https://github.com/cross-rs/cross` but it failed with following error

```
error[E0599]: no variant or associated item named `Stdin` found for enum `Stream` in the current scope
   --> src/shell.rs:458:57
    |
458 |     const OWO: owo_colors::Stream = owo_colors::Stream::Stdin;
    |                                                         ^^^^^ variant or associated item not found in `Stream`
```

After debugging found that it installs  owo-colors v3.6.0 which does not have `Stdin`, you can check [here](https://docs.rs/owo-colors/latest/owo_colors/enum.Stream.html).

```
gitpod /workspace/relayer (main) $ cargo install cross --git https://github.com/cross-rs/cross
    Updating git repository `https://github.com/cross-rs/cross`
    Updating git submodule `https://github.com/cross-rs/cross-toolchains.git`
  Installing cross v0.2.4 (https://github.com/cross-rs/cross#aa59bf24)
    Updating crates.io index
  Downloaded serde v1.0.152
  Downloaded addr2line v0.19.0
  Downloaded unicode-ident v1.0.6
  Downloaded thiserror-impl v1.0.38
  Downloaded semver v1.0.16
  Downloaded clap_lex v0.3.0
  Downloaded os_str_bytes v6.4.1
  Downloaded toml v0.5.10
  Downloaded syn v1.0.107
  Downloaded which v4.3.0
  Downloaded is-terminal v0.4.2
  Downloaded backtrace v0.3.67
  Downloaded thiserror v1.0.38
  Downloaded clap_derive v4.0.21
  Downloaded miniz_oxide v0.6.2
  Downloaded cc v1.0.78
  Downloaded clap v4.0.32
  Downloaded ryu v1.0.12
  Downloaded serde_derive v1.0.152
  Downloaded proc-macro2 v1.0.49
  Downloaded itoa v1.0.5
  Downloaded serde_ignored v0.1.6
  Downloaded quote v1.0.23
  Downloaded once_cell v1.16.0
  Downloaded termcolor v1.1.3
  Downloaded io-lifetimes v1.0.3
  Downloaded dirs-sys v0.3.7
  Downloaded serde_json v1.0.91
  Downloaded owo-colors v3.6.0

```

**Comment by Emilgardis** [comment]
Hi! Thanks for the report, I've filed an issue upstream (however we should also just fix the issue).

To workaround this, we recommend to install cross with the `--locked` toggle


```
cargo install cross --locked
```

**Comment by Emilgardis** [comment]
If you're using `actions-rs/cargo@v1` with `use-cross: true`, you should be able to circumvent this by installing cross manually before the step to `use-cross`


```
      - run: cargo install cross --locked
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: check
```

or if you have a matrix for cross-compilation

```
      - run: cargo install cross --locked
        if: matrix.use-cross
      - uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.use-cross }}
          command: check
```

I'd highly recommend also going away from `actions-rs`, see https://github.com/actions-rs/toolchain/issues/216
