### ISSUE TITLE
Is there a way config cross using `lld` instead of `ld`.

### ISSUE THREAD

**Issue by yuyang-ok** [cross-rs/cross#1200]
`ld` is really slow.

**Comment by Emilgardis** [comment]
Sure!

All that is needed is for you to install lld, and then use it as the linker

```
[build]
rustflags = [
  "-C", "link-arg=-fuse-ld=lld",
]
```

now, the tricky part is installing it, either install it with

```toml
[build]
pre-build = [
    "apt-get update && apt-get install --assume-yes --no-install-recommends lld",
]
```


You can also use `rust-lld` as provided by `rustup component add --toolchain <toolchain-used-by-cross> llvm-tools` (where `<toolchain-used-by-cross>` would most likely be `stable-x86_64-unknown-linux-gnu`) and then setting the linker to `rust-lld` provided that it's in path or specifying the full path. This would be hugely improved with #716 and and allowing it to use [`cargo-binutils`](https://github.com/rust-embedded/cargo-binutils)
