### ISSUE TITLE
Private Crate Repository Issues

### ISSUE THREAD

**Issue by josh-bpl** [cross-rs/cross#1206]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

I am trying to use cross to cross compile my project for a `armv7-unknown-linux-gnueabihf` (although this issue is also present when using cross to target the host target architecture) target using a Gitlab CI/CD shared runner. I have seen the [Gitlab CI sample](https://github.com/cross-rs/cross/wiki/FAQ#gitlab-ci) and the [cross remote documentation](https://github.com/cross-rs/cross/wiki/Remote), both of which I have implemented the best I can tell.

The issue I have is that my project contains dependencies to private Gitlab repositories. I saw the data volumes section of the cross remote documentation and have tried setting `CROSS_REMOTE_COPY_REGISTRY` and `CROSS_REMOTE_COPY_CACHE` environment variables, but whatever I do, cross always tries to fetch my private repos at compile time - and of course fails because it cannot authenticate. Before running the cross build command I have tried running `cargo update` and `` but still the same issue. It appears as though maybe it fails to copy over the cached packages?

I even tried adding this to my Cross.toml to use the job token and https to clone the private crates (with `CARGO_NET_GIT_FETCH_WITH_CLI` set.) but it still failed - almost like the pre-build command was not run.

```toml
[build.armv7-unknown-linux-gnueabihf]
build-std = false
xargo = false
pre-build = [
    "git config --global url.\"https://gitlab-ci-token:$CI_JOB_TOKEN@gitlab.com/\".insteadOf \"ssh://git@gitlab.com/\""
]
```

I have spent several days experimenting with all the options and am at the point where it looks like it might be an issue with cross - although my user error is always a possibility.

Related issues:
#401 

### What target(s) are you cross-compiling for?

armv7-unknown-linux-gnueabihf

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.5

### Example

# .gitlab-ci.yml

```yaml
image: "rust:latest"

stages:
  - build
  - test
  - doc

cargo:build_armv7l:
  stage: build
  services:
    - docker:19.03.12-dind
  before_script:
    - rustup target list --installed
    - export PATH=$PATH:$CARGO_HOME/bin/
    - apt -qq update
    - apt install -yqq git
    - apt-get install -yqq --no-install-recommends build-essential libudev-dev llvm-dev clang libclang-dev libusb-1.0-0-dev libudev-dev
  variables:
    CI_DEBUG_SERVICES: "true"
    GIT_SUBMODULE_STRATEGY: recursive
    # the host where the docker instance is running
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_DRIVER: "overlay2"
    # ensure cross knows it's running remotely
    CROSS_REMOTE: "1"
    # Copy cargo registry and cache to cross instance
    CROSS_REMOTE_COPY_REGISTRY: "1"
    DOCKER_TLS_CERTDIR: ""

  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval "$(ssh-agent)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    - apt -qq update
    - apt install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common > /dev/null
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - apt -qq update
    - apt install -y docker-ce > /dev/null

    - rustc --version && cargo --version # Print version info for debugging
    - cargo install cross
    - cargo clean
    - cargo metadata --format-version=1 --filter-platform armv7-unknown-linux-gnueabihf
    # kill the SSH agent, to ensure it works
    - eval 'ssh-agent -k'
    - cross build --verbose --armv7-unknown-linux-gnueabihf

  artifacts:
    when: always
    paths:
      - $CI_PROJECT_DIR/target/release/my_project
```

# Job logs

[job_log.txt](https://github.com/cross-rs/cross/files/10688972/job_log.txt)
