### ISSUE TITLE
Problems linking external dependency for Windows (x86_64-pc-windows-gnu)

### ISSUE THREAD

**Issue by asiryk** [cross-rs/cross#1211]
I'm trying to compile [this minimal project](https://github.com/asiryk/cross-dotnet) that uses [netcorehost](https://crates.io/crates/netcorehost) library which is dependent on .NET nethost C library.

netcorehost has feature of vendoring the C library enabled. But for some reason I get a lot of linking errors.

```
/usr/bin/x86_64-w64-mingw32-ld: /target/x86_64-pc-windows-gnu/debug/build/nethost-sys-80657266afb68e28/out/nethost/win-x64/libnethost.lib(nethost/CMakeFiles/libnethost.dir/__/hostmisc/longfile.windows.cpp.obj):(.text$di+0x19): undefined reference to `??$_Construct@$00PEB_W@?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@AEAAXQEB_W_K@Z'
```

I'm building on `macOS, arm64 (Apple M1 Pro)` for `x86_64-pc-windows-gnu` using `Docker`.

---

I've tried to build this [dbus project from Wiki](https://github.com/cross-rs/wiki_assets/tree/main/FAQ/dbus) for both `x86_64-pc-windows-gnu` and `x86_64-unknown-linux-gnu` targets using this configuration https://github.com/asiryk/cross-dbus with default cross commands: `cross build --target x86_64-unknown-linux-gnu` & `cross build --target x86_64-pc-windows-gnu`

```toml
[dependencies]
dbus = "0.9.5"

[package.metadata.cross.target.x86_64-pc-windows-gnu]
pre-build = [
    "apt-get update",
    "apt-get install -y libdbus-1-dev pkg-config libdbus-1-3",
]

[package.metadata.cross.target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update",
    "apt-get install -y libdbus-1-dev pkg-config libdbus-1-3",
]
```

The Linux one successfully compiled, but for Windows I got the same linking errors.

```
/usr/bin/x86_64-w64-mingw32-ld: /target/x86_64-pc-windows-gnu/debug/deps/libdbus-63c0f4b960444f7e.rlib(dbus-63c0f4b960444f7e.dbus.884bbf66-cgu.11.rcgu.o): in function `dbus::ffidisp::watch::WatchList::watch_handle'
```

---

So am I doing something wrong? Does Wine require some special configuration to "see" the external libraries I'm linking against? Or this is the bug in cross?
