### ISSUE TITLE
Android build seems to be broken after Rust 1.68

### ISSUE THREAD

**Issue by Nugine** [cross-rs/cross#1217]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

My CI fails on the following targets after Rust 1.68 released.

+ aarch64-linux-android
+ i686-linux-android
+ x86_64-linux-android

[CI log](https://github.com/Nugine/rlimit/actions/runs/4395735299/jobs/7697735320#step:6:149)
[Workflow file](https://github.com/Nugine/rlimit/blob/fbf085ea9aef192fc7eaec39fb1710b9cf7e716f/.github/workflows/ci.yml#L128-L144)

I don't know how to fix it.

### What target(s) are you cross-compiling for?

aarch64-linux-android, i686-linux-android, x86_64-linux-android

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross v0.2.5

**Comment by Emilgardis** [comment]
with 1.68, rust updated the minimal ndk. See https://blog.rust-lang.org/2023/01/09/android-ndk-update-r25.html

The current images for 0.2 use `r21d`, the images from `main` use `r25b` as of https://github.com/cross-rs/cross/pull/1023

To fix this, but still using `cross 0.2.5`, please specify the image the android builds are using as

```toml
[target.aarch64-linux-android]
image = "ghcr.io/cross-rs/aarch64-linux-android:main"
[target.i686-linux-android]
image = "ghcr.io/cross-rs/i686-linux-android:main"
[target.x86_64-linux-android]
image = "ghcr.io/cross-rs/x86_64-linux-android:main"
```

or use a environment variable

```env
CROSS_TARGET_AARCH64_LINUX_ANDROID_IMAGE="ghcr.io/cross-rs/aarch64-linux-android:main"
CROSS_TARGET_I686_LINUX_ANDROID_IMAGE="ghcr.io/cross-rs/i686-linux-android:main"
CROSS_TARGET_X86_64_LINUX_ANDROID_IMAGE="ghcr.io/cross-rs/x86_64-linux-android:main"
```

or simply use cross installed from `main` (we do not provide a compiled binary for that though)
