### ISSUE TITLE
Cross compiling on M1 Mac gives weird linker error

### ISSUE THREAD

**Issue by korken89** [cross-rs/cross#1241]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

When building an app with the following `cross` config we get a linking error that was unexpected and googling it does not really give insight into the error.

Cross.toml

```toml
[target.x86_64-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install -y pkg-config gcc libssl-dev openssl libcrypto++8 mosquitto-dev libclang-dev "]
image = "ubuntu:22.04"
```

Build command:

```
DOCKER_BUILDKIT=1 \
cross build --release --target x86_64-unknown-linux-gnu
```

Error:

```
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

Building this on a Linux (arch) computer works fine, but on an M1 Mac it fails.

Any hints on what might be wrong?

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [ ] x86_64 / AMD64
- [ ] arm32
- [X] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.5

### Example

Cross.toml

```toml
[target.x86_64-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install -y pkg-config gcc libssl-dev openssl libcrypto++8 mosquitto-dev libclang-dev "]
image = "ubuntu:22.04"
```

Build command:

```
DOCKER_BUILDKIT=1 \
cross build --release --target x86_64-unknown-linux-gnu
```

### Additional information / notes

It builds on an Arch Linux computer
