### ISSUE TITLE
Cross build for x86_64-apple-darwin fails on openssl, ranlib malformed archive

### ISSUE THREAD

**Issue by xrl** [cross-rs/cross#1243]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

I am compiling a project with cross for the first time, I am targeting `x86_64-apple-darwin` and failing. The CI system runs on r5.2xlarge's in AWS, regular Intel servers. I have posted a full copy of the build failure in this gist: https://gist.github.com/xrl/208a57f721e673e8ace2666c16ae87d1 . And for more context, here are my project's configurations:

```
# Cargo.toml
[package]
name = "ents-cli"
version = "0.3.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ents"

[dependencies]
aws-arn = "0.2.0"
aws-config = "0.55.0"
aws-sdk-ecr = "0.25.1"
base64 = "0.13.0"
chrono = "0.4.19"
clap = "3.0.0-rc.0"
dirs-next = "2"
env_logger = "0"
eyre = "0"
futures-util = "0.3"
http = "0.2.4"
k8s-openapi = { version = "0.17.0", features = ["v1_25"] }
kube = { version="=0.80.0", default-features = false, features = ["client"] }
lazy_static = "1"
log = "0"
openssl = { version = "0.10", features = ["vendored"] }
phf = { version = "0.10.0", features = ["macros"] }
prettytable-rs = "0.8.0"
rancher = "0"
reqwest = "0"
semver = "1"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_yaml = "0.8.17"
tokio = { version = "1", features = ["full"]}
tokio-stream = { version = "0" }
which = "4"
```

and I figured out how to use build my own OS X SDKs (turns out I had an SDK kicking around from a rust-musl-builder attempt). I am using `MacOSX12.0.sdk.tar.xz` which I package for my own use. And I create my Darwin cross images in my CI with these steps:

```
steps:
  - name: build
    image: ubuntu:22.04
    pull: always
    resources:
      cpu: 3700m
      memory: 62000MiB
    environment:
      SDK_URL: https://my-sdk-hosting/macos-sdks/MacOSX12.0.sdk.tar.xz
    commands:
      - apt-get update > /dev/null; apt-get install -y docker.io curl > /dev/null
      - curl -O https://ids-dev-artifacts.s3.amazonaws.com/ents-cli/0.3.3/ents-x86_64-unknown-linux-musl; chmod a+x ents-*; mv ents-* /usr/local/bin/ents
      - ents ecr docker-login --stripe-group=ids --only=ids-dev
      - git submodule update --init --remote
      - cd docker/
      - docker build -t $REPO:x86_64-apple-darwin -f cross-toolchains/docker/Dockerfile.x86_64-apple-darwin-cross --build-arg "MACOS_SDK_URL=$SDK_URL" .
      - docker build -t $REPO:aarch64-apple-darwin -f cross-toolchains/docker/Dockerfile.aarch64-apple-darwin-cross --build-arg "MACOS_SDK_URL=$SDK_URL" .
      - docker push $REPO:x86_64-apple-darwin; docker push $REPO:aarch64-apple-darwin
```

those images are then referenced from my Rust project:

```
# Cross.toml
[target.aarch64-apple-darwin]
image = "539703851677.dkr.ecr.us-west-2.amazonaws.com/cross:aarch64-apple-darwin"

[target.x86_64-apple-darwin]
image = "539703851677.dkr.ecr.us-west-2.amazonaws.com/cross:x86_64-apple-darwin"
```

and finally my CI pipeline triggering the work:

```
# .drone.yml
---
kind: pipeline
type: kubernetes
name: default

metadata:
  namespace: drone
  labels:
    app: ents-cli
  annotations:
    iam.amazonaws.com/role: k8s-drone
service_account_name: drone-build-sa

environment:
  RUST_VERSION: 1.68.1
  DEBIAN_FRONTEND: noninteractive
  AWS_REGION: us-west-2
  CROSS_VERSION: 0.2.5
  DOCKER_HOST: tcp://localhost:2375

services:
  - name: docker
    image: docker:dind
    privileged: true
    entrypoint: ["dockerd", "--host=tcp://0.0.0.0:2375"] # work around for default TLS. I don't want to bother sharing the cert dir.

workspace:
  path: /root

steps:
  - name: cross-compile-all-targets
    image: ubuntu:22.04
    pull: always
    resources:
      cpu: 3700m
      memory: 62000MiB
    commands:
      - apt-get update > /dev/null; apt-get install -y curl build-essential docker.io time > /dev/null
      - curl -O https://ids-dev-artifacts.s3.amazonaws.com/ents-cli/0.3.3/ents-x86_64-unknown-linux-musl; chmod a+x ents-*; mv ents-* /usr/local/bin/ents
      - ents ecr docker-login --stripe-group=ids --only=ids-dev
      - time curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$RUST_VERSION --target x86_64-apple-darwin aarch64-apple-darwin -y
      - . "$HOME/.cargo/env"
      - cargo fmt --check
      - time curl -LO --silent https://github.com/cross-rs/cross/releases/download/v$CROSS_VERSION/cross-x86_64-unknown-linux-gnu.tar.gz; tar xzf cross-*.tar.gz; mkdir -p ~/.cargo/bin; mv cross ~/.cargo/bin
      - for TARGET in x86_64-unknown-linux-musl x86_64-apple-darwin aarch64-apple-darwin; do echo "==================\n===== WORKING ON $TARGET =====\n=================="; time cross build --target $TARGET --release; mv target/$TARGET/release/ents target/$TARGET/release/ents-$TARGET; done
```

### What target(s) are you cross-compiling for?

other (specify in description)

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.4.2
