### ISSUE TITLE
error: linker `clang` not found when using windows crate

### ISSUE THREAD

**Issue by ItsEthra** [cross-rs/cross#1268]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

Hello, I am trying to cross compile `x86_64-pc-windows-gnu` from my main arch linux machine `x86_64-unknown-linux-gnu`. Currently compilation of a binary depended on `windows` crate does not work, I get this error.
```
error: linker `clang` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `windows_x86_64_gnu` (build script) due to previous error
```

My system:
* cross: `0.2.5`
* cargo: `1.71.0-nightly (09276c703 2023-05-16)`
* rustc: `1.71.0-nightly (9d871b061 2023-05-21)`

### What target(s) are you cross-compiling for?

x86_64-pc-windows-gnu

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [X] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.5

### Example

```toml
# cargo.toml
[package]
name = "crosswin"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = "0.48.0"
```

```rust
// main.rs
fn main() {}
```

### Additional information / notes

Builds fine without `windows` crate

**Comment by Emilgardis** [comment]
looks like something needs clang
I can't replicate your issue using the example you've provided, do you maybe have a `./cargo/config.toml` file with a custom linker set? cc #621

see this [wiki entry](https://github.com/cross-rs/cross/wiki/FAQ#using-clang--bindgen)

**Comment by ItsEthra** [comment]
Hm, the only cargo config  I have is in my home folder which has this, I doubt it causing issues. Should I create a repo to reproduce the issue? For me it breaks just as I add `windows = "0.48.0"` to dependencies of a hello world binary.
```toml
[registries.crates-io]
protocol = "sparse"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold", "--cfg", "tokio_unstable"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
```
