### ISSUE TITLE
How to integrate Cross with Gitlab CI?

### ISSUE THREAD

**Issue by hanusek** [cross-rs/cross#1507]
Hello.
I use [docker runner in Gitlab CI](https://docs.gitlab.com/runner/install/docker.html). I would like to use Cross in CI. 
How do it?

**Comment by Emilgardis** [comment]
See https://github.com/cross-rs/cross/issues/273 and https://github.com/cross-rs/cross/wiki/FAQ#gitlab-ci

**Comment by t-moe** [comment]
Is it possible that the linked FAQ is out of date?

i always get 

> Error: 
>    0: no container engine found

here my gitlab ci conf

```
image: "rust:latest"
build:raspy:cfw:
  stage: build
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    CROSS_REMOTE: 1

    DOCKER_TLS_CERTDIR: ""
    FF_NETWORK_PER_BUILD: "true" # doesnt matter if i add this or not
  services:
    - docker:18.09-dind # doesnt matter if i use latest version or 18.09
  before_script:
    - cargo install cross

  script:
    - cross build --bin cfw --features cli

```

or do i need to run a different image?  (one that replaces cross with some wrapper script?)
