### ISSUE TITLE
 `cargo: not found` when using `cross` in GitHub Actions

### ISSUE THREAD

**Issue by sundaram123krishnan** [cross-rs/cross#1528]
I am encountering an issue when using `cross` in my GitHub Actions workflow. The error message indicates that `cargo` is not found.

This occurs during the build step in my CI pipeline. Below is the relevant portion of my GitHub Actions configuration:

```yaml
jobs: 
  test:
    name: test
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: [ aarch64-unknown-linux-gnu ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --bin piggui --release --features "gui","pi_hw" --target ${{ matrix.target }}
 ```

The build fails with the error:
```
sh: 1: cargo: not found
```
But when i try to list `cargo` packages: 
```
ls /root/.cargo/bin
```
`cross` is present.

What is the cause of this strange behavior?
Any help is much appreciated!
Thx in advance!
