### ISSUE TITLE
Gitlab CI Fails

### ISSUE THREAD

**Issue by t-moe** [cross-rs/cross#1530]
Is it possible that the linked FAQ is out of date?

i always get 

> Error: 
>    0: no container engine found

here is my example repo https://gitlab.com/t-moe/cross-gitlab-ci-test/-
with an example run: https://gitlab.com/t-moe/cross-gitlab-ci-test/-/jobs/7403785591

_Originally posted by @t-moe in https://github.com/cross-rs/cross/issues/1507#issuecomment-2243188429_

**Comment by Emilgardis** [comment]
Do you mean https://github.com/cross-rs/cross/wiki/FAQ#gitlab-ci ? It might be :/

This might be interesting https://github.com/cross-rs/cross/issues/1351#issuecomment-2209463985 however

**Comment by t-moe** [comment]
Yes, I mean that one.

I read that comment, but this also does not resolve the issue:

> 
> Using docker image sha256:074f1687a41ccf251dae357352554e41bd8168aecd480acab710389d6f78837d for docker:18.09 with digest docker@sha256:58469a43b529313091f1df424037895a9961b27149aafec812ce8fd8d7ac0c9d ...
> $ printenv | grep -v "^HOSTNAME=" > env.list
> $ docker run --rm --env-file env.list -v /var/run/docker.sock:/var/run/docker.sock rust:latest bash -c "git clone $CI_REPOSITORY_URL /data && cd /data/ && cross -v build"
> docker: error during connect: Post http://docker:2375/v1.39/containers/create: dial tcp: lookup docker on 127.0.0.11:53: no such host.

**Comment by Emilgardis** [comment]
try using cross from the main branch

**Comment by t-moe** [comment]
Same or similar error.  I've tried various workarounds, listed in the issue tracker. None of them seemd to work. (Sorry for not having them listed out here, for further reference).

In the end I had to pivot to manually invoking cross on my developer machine, because I could not spend more time on this issue :(.

**Comment by Emilgardis** [comment]
Sorry you're having issues! I've not experimented with gitlab too much so I'm not super familiar, hopefully I can get some time to look into the woes people are having with it + cross

**Comment by crespum** [comment]
I'm experiencing the same issue. Has anyone managed to fix it?

**Comment by SolidTux** [comment]
Not OP, but the following works for me:

```yaml
stages:
  - build

build:aarch64:
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    CROSS_REMOTE: 1
  image: rust:slim
  services:
    - docker:dind
  stage: build
  before_script:
    - apt update
    - apt install -y docker-cli curl
    - curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - cargo binstall cross
  script:
    - cross build --release --target aarch64-unknown-linux-musl
    - cp "target/aarch64-unknown-linux-musl/release/$CI_PROJECT_NAME" "${CI_PROJECT_NAME}-aarch64"
  artifacts:
    paths:
      - ${CI_PROJECT_NAME}-aarch64
```
