### ISSUE TITLE
Ability to set default build target

### ISSUE THREAD

**Issue by Progdrasil** [cross-rs/cross#368]
It would be useful for those who develop for one specific target to be able to define the default build target. In much the same way [cargo does]. This would reduce the following example command:
```console
cross build --target armv7-unknown-linux-gnueabihf 
```
To the equivalent `Cross.toml` and command
```toml
[build]
target = "armv7-unknown-linux-gnueabihf"
```
```console
cross build
```

[cargo does]: https://doc.rust-lang.org/cargo/reference/config.html#buildtarget
