### ISSUE TITLE
target.arm-unknown-linux-gnueabihf.image doesn't work

### ISSUE THREAD

**Issue by hombit** [cross-rs/cross#414]
Default image used by `cross` is broken for `arm-unknown-linux-gnueabihf`, `rustembedded/cross:arm-unknown-linux-gnueabihf-0.2.0` (see #391). But after I specified image fixed in #397 in my Caro.toml (see bellow), `cross` continued to use default image.

Command I run:
```sh
cross build --release --target=arm-unknown-linux-gnueabihf
```

`Cargo.toml` modification I made:
```toml
[target.arm-unknown-linux-gnueabihf]
image = "rustembedded/cross:arm-unknown-linux-gnueabihf"
```

Tested on both `0.2.0` and current `master` (5d717f08)
