### ISSUE TITLE
Add pre-build hook

### ISSUE THREAD

**Issue by andrewbanchich** [cross-rs/cross#565]
I'd like to use an official image like `centos/devtoolset-7-toolchain-centos7`, which I can do by adding to my `Cross.toml`. However, the image doesn't come with `openssl` installed. It seems like overkill to have to create and maintain a Dockerfile, then add an extra build script to my CI just to get `openssl`.

Instead, would it be possible to do something like this?
```toml
[target.x86_64-unknown-linux-gnu]
image = "centos/devtoolset-7-toolchain-centos7"
pre-build = "yum install openssl-devel"
```

**Comment by Emilgardis** [comment]
This has been implemented!

```toml
[target.x86_64-unknown-linux-gnu]
image = "centos/devtoolset-7-toolchain-centos7"
pre-build = ["yum install openssl-devel"]
```

should just work now with latest cross :)
