### ISSUE TITLE
Update `build-std` to support a boolean or array.

### ISSUE THREAD

**Issue by Alexhuszagh** [cross-rs/cross#896]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar request
- [ ] This feature could be solved with a [custom docker image](https://github.com/cross-rs/cross#custom-docker-images) (optional)

### Describe your request

When using `-Z build-std`, `cargo` also enables you to pass various different [flags](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std) which will specify the exact components to build, rather than all components. This can be useful if `std` isn't supported, but `core` and `alloc` are. Therefore, `build-std` could be provided as an array or bool (we shouldn't allow a table), and then passed transparent to `-Z build-std`.

```toml
[target.x86_64-unknown-dragonfly]
build-std = true

[target.thumbv6m-none-eabi]
build-std = ["core", "alloc"]
```

### Describe why this would be a good inclusion for `cross`

Allows more comprehensive use of `build-std`, without breaking old behavior.
