### ISSUE TITLE
environment variables are not passed

### ISSUE THREAD

**Issue by hazkell** [cross-rs/cross#912]
### Checklist

- [X] I've looked through the [issues and pull requests](https://github.com/cross-rs/cross/issues?q=) for similar reports

### Describe your issue

cross stopped compiling after last update.
I am using environment variables and now they are not passed for the following targets:
- x86_64-unknown-linux-musl
- i686-unknown-linux-musl
- arm-unknown-linux-musleabi
- aarch64-unknown-linux-musl

I do have the Cross.toml file and I am able to see environment variables in the debug output of the action.

### What target(s) are you cross-compiling for?

aarch64-unknown-linux-musl, arm-unknown-linux-musleabi, i686-unknown-linux-musl, x86_64-unknown-linux-musl

### Which operating system is the host (e.g computer cross is on) running?

- [ ] macOS
- [ ] Windows
- [X] Linux / BSD
- [ ] other OS (specify in description)

### What architecture is the host?

- [ ] x86_64 / AMD64
- [ ] arm32
- [ ] arm64 (including Mac M1)

### What container engine is cross using?

- [X] docker
- [ ] podman
- [ ] other container engine (specify in description)

### cross version

cross 0.2.2

### Example

```
- name: Build release
  uses: actions-rs/cargo@v1
  env:
    SOM_KEY: ${{ secrets.SOME_KEY }}
    TARGET: ${{ matrix.binary_target }}${{ matrix.ext }}
  with:
    use-cross: true
    command: build
    args: --release --target ${{ matrix.binary_target }}
```

**Comment by Alexhuszagh** [comment]
This is a bug I believe that was documented in #863 and patched in #867. Try setting them in `build.env` as a temporary workaround or install from git (`cargo install cross --git https://github.com/cross-rs/cross`). We should be releasing 0.2.3 with this patch very soon.

**Comment by hazkell** [comment]
Cross.toml
```
[build.env]
passthrough = [
    "SOME_KEY"
]
```

Temporarily switched to 0.2.1 and it still gives the same error, therefore must be unrelated to 0.2.2.
here is the github actions log (if it is not enough, tell which parts should I include):
```
Run actions-rs/cargo@v1
  with:
    use-cross: true
    command: build
    args: --verbose  --release --target x86_64-unknown-linux-musl
  env:
    SOME_KEY: ***

Installing "cross = latest"

cross build --verbose --release --target x86_64-unknown-linux-musl
+ cargo metadata --format-version 1 --filter-platform x86_64-unknown-linux-musl
+ rustc --print sysroot
+ rustup toolchain list
+ rustup target list --toolchain stable-x86_64-unknown-linux-gnu
+ rustup component list --toolchain stable-x86_64-unknown-linux-gnu
+ rustup component add rust-src --toolchain stable-x86_64-unknown-linux-gnu
info: downloading component 'rust-src'
info: installing component 'rust-src'
+ /usr/bin/docker
+ /usr/bin/docker run --userns host -e 'PKG_CONFIG_ALLOW_CROSS=1' -e 'XARGO_HOME=/xargo' -e 'CARGO_HOME=/cargo' -e 'CARGO_TARGET_DIR=/target' -e 'CROSS_RUNNER=' -e 'USER=runner' --rm --user 1001:121 -v /home/runner/.xargo:/xargo:Z -v /home/runner/.cargo:/cargo:Z -v /cargo/bin -v /home/runner/work/xxx/xxx:/project:Z -v /home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu:/rust:Z,ro -v /home/runner/work/xxx/xxx/target:/target:Z -w /project rustembedded/cross:x86_64-unknown-linux-musl-0.2.1 sh -c 'PATH=$PATH:/rust/bin cargo build --verbose --release --target x86_64-unknown-linux-musl'
Unable to find image 'rustembedded/cross:x86_64-unknown-linux-musl-0.2.1' locally
x86_64-unknown-linux-musl-0.2.1: Pulling from rustembedded/cross
```

Code producing the issue:
```
-- consts.rs
const some_key: &str = env!("SOME_KEY");
```

**Comment by Emilgardis** [comment]
Why are you using an old image with 0.2.2?

Can you post the full `Cross.toml`?

**Comment by hazkell** [comment]
this is full `Cross.toml`

**Comment by hazkell** [comment]
```
[build.env]
passthrough = [
    "SOME_KEY"
]

[target.aarch64-unknown-linux-musl]
image = "rustembedded/cross:aarch64-unknown-linux-musl-0.2.1"

[target.arm-unknown-linux-musleabi]
image = "rustembedded/cross:arm-unknown-linux-musleabi-0.2.1"

[target.i686-unknown-linux-musl]
image = "rustembedded/cross:i686-unknown-linux-musl-0.2.1"

[target.x86_64-unknown-linux-musl]
image = "rustembedded/cross:x86_64-unknown-linux-musl-0.2.1"
```

**Comment by hazkell** [comment]
> Why are you using an old image with 0.2.2?
> 
> Can you post the full `Cross.toml`?

I thought the issue was with 0.2.2 as 0.2.1 was passing, but it seems that something was changed in code.

**Comment by Emilgardis** [comment]
Aha, I see, you've not actually tested 0.2.1 then, the images don't contain any code for how the environment variables are passed to docker. To test 0.2.1 you need to have 0.2.1 installed

Instead, try installing cross from current main, you can do this in ci before your `use-cross: true` action

```
- name: Install cross from main
  run: cargo install cross --git https://github.com/cross-rs/cross
- name: Build release
  uses: actions-rs/cargo@v1
  env:
    SOM_KEY: ${{ secrets.SOME_KEY }}
    TARGET: ${{ matrix.binary_target }}${{ matrix.ext }}
  with:
    use-cross: true
    command: build
    args: --release --target ${{ matrix.binary_target }}
```

this issue is very much what was described in #863 

We will have a 0.2.3 version out soon, but above will work well
